# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFg3VENEfc8fX0lVDHmGyy7_I00wnyhI
"""

sumEven = 0
numberInput = int(input())
for i in range(numberInput+1):
  if i % 2 == 0:
    sumEven += i
print(sumEven)